// examples/react/src/components/ValidComponent.tsx
import React from 'react'

/**
 * ValidComponent - All class names used here should pass validation
 *
 * This component uses:
 * - CSS classes from app.css: container, header, main-content
 * - SCSS classes from components.scss: button-primary, card, alert
 * - Tailwind utilities: flex, items-center, justify-between, gap-4, bg-blue-500, text-white, p-4, rounded
 * - Tailwind custom theme: text-brand-500
 * - Whitelist pattern: custom-widget (matches custom-*)
 * - Ignored pattern: dynamic-loader (matches dynamic-*, should not error even though it doesn't exist)
 */
export const ValidComponent: React.FC = () => {
  return (
    <div className="container mb-2">
      <header className="header flex items-center justify-between">
        <h1 className="text-brand-500">Valid Component</h1>
        <nav className="flex gap-4">
          <button className="button-primary">Primary</button>
        </nav>
      </header>

      <main className="main-content">
        <div className="card">
          <h2 className="text-white bg-blue-500 p-4 rounded">Card Title</h2>
          <div className="alert">This is an alert message</div>
        </div>

        {/* Whitelist pattern - should be valid */}
        <div className="custom-widget">Custom widget content</div>

        {/* Ignored pattern - should not error even though it doesn't exist */}
        <div className="dynamic-loader">Dynamic loader</div>
      </main>
    </div>
  )
}

// examples/vue/src/components/ValidComponent.vue
<template>
  <div class="container mb-4">
    <!-- Header with CSS classes -->
    <header class="header">
      <div class="nav">
        <a href="#" class="nav-link">Home</a>
        <a href="#" class="nav-link">About</a>
        <a href="#" class="nav-link">Contact</a>
      </div>
    </header>

    <!-- Main content with mixed CSS/SCSS/Tailwind -->
    <main class="main-content">
      <h1 class="title text-brand-500">Valid Vue Component</h1>
      <p class="text-lg text-gray-700 mb-4">
        This component demonstrates valid class names from CSS, SCSS, and Tailwind.
      </p>

      <!-- Section with Tailwind utilities -->
      <section class="section">
        <h2 class="subtitle">Tailwind Utilities</h2>
        <div class="flex gap-4 items-center justify-between">
          <div class="bg-blue-500 text-white p-4 rounded">Box 1</div>
          <div class="bg-green-500 text-white p-4 rounded">Box 2</div>
          <div class="bg-red-500 text-white p-4 rounded">Box 3</div>
        </div>
      </section>

      <!-- Card with CSS classes -->
      <section class="section">
        <div class="card">
          <h3 class="subtitle">Card Example</h3>
          <p>This card uses CSS classes from app.css</p>
        </div>
      </section>

      <!-- Buttons using SCSS -->
      <section class="section">
        <h2 class="subtitle">Buttons (SCSS)</h2>
        <div class="flex gap-4">
          <button class="button-primary">Primary Button</button>
          <button class="button-secondary">Secondary Button</button>
        </div>
      </section>

      <!-- Alerts from SCSS -->
      <section class="section">
        <h2 class="subtitle">Alerts (SCSS)</h2>
        <div class="alert alert-info">This is an info alert</div>
        <div class="alert alert-warning">This is a warning alert</div>
        <div class="alert alert-success">This is a success alert</div>
      </section>

      <!-- Badge utilities -->
      <section class="section">
        <h2 class="subtitle">Badges</h2>
        <div class="flex gap-4">
          <span class="badge badge-success">Success</span>
          <span class="badge badge-error">Error</span>
        </div>
      </section>

      <!-- Ignored patterns - should not error -->
      <div class="dynamic-loader">This class matches ignore pattern dynamic-*</div>
      <div class="custom-widget">This class matches ignore pattern custom-*</div>
    </main>

    <!-- Footer -->
    <footer class="footer">
      <p class="text-center text-gray-500">© 2024 Vue Example</p>
    </footer>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'

export default defineComponent({
  name: 'ValidComponent',
})
</script>
